### ISSUE TITLE
spotify customization

### ISSUE THREAD

**Issue by kylesferrazza** [kylesferrazza/nix#30]
with `spicetify`? - see `spicetify` branch

`spicetify` seems to require write access to the spotify binary, but maybe this can happen during spotify's packaging (make the spicetify package wrap the spotify package)?

**Comment by Pablo1107** [comment]
Did you find some way to wrap the spotify package with spicetify?

**Comment by kylesferrazza** [comment]
@Pablo1107 not yet :(

Let me know if you figure it out before I do!

**Comment by Pablo1107** [comment]
I try some things the other day. You can basically make an overlay for spotify and override the `postInstall` hook, I think we can run spicetify from there and specify the folder from the `$out` of the derivation.

It would be tedious to maintain tho.

**Comment by Pablo1107** [comment]
I tried with the `postInstall` hook but it didn't work because it also need the pref folder, which is created in the home directory and when Spotify is first launched. Maybe `home-manager`?

**Comment by kylesferrazza** [comment]
@Pablo1107 
this is working, #31 merged in solarized spotify!

**Comment by Pablo1107** [comment]
Great news!
