### ISSUE TITLE
upstream multilockscreen

### ISSUE THREAD

**Issue by kylesferrazza** [kylesferrazza/nix#40]
PR into nixpkgs

**Comment by jerbaroo** [comment]
https://github.com/NixOS/nixpkgs/issues/99637

**Comment by kylesferrazza** [comment]
Upstreamed in https://github.com/NixOS/nixpkgs/pull/99688.
Need to update to use `multilockscreen` from master, and create a new issue to unpin it once it is included in the unstable channel.
